// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Greqptc.proto

package com.fireflyi.gerant.rpclient.protobuf;

public interface GreqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.Greq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *聊天类型
   * </pre>
   *
   * <code>string cmdId = 1;</code>
   */
  java.lang.String getCmdId();
  /**
   * <pre>
   *聊天类型
   * </pre>
   *
   * <code>string cmdId = 1;</code>
   */
  com.google.protobuf.ByteString
      getCmdIdBytes();

  /**
   * <code>string reqMsg = 2;</code>
   */
  java.lang.String getReqMsg();
  /**
   * <code>string reqMsg = 2;</code>
   */
  com.google.protobuf.ByteString
      getReqMsgBytes();

  /**
   * <pre>
   *发送请求用户id
   * </pre>
   *
   * <code>string uid = 3;</code>
   */
  java.lang.String getUid();
  /**
   * <pre>
   *发送请求用户id
   * </pre>
   *
   * <code>string uid = 3;</code>
   */
  com.google.protobuf.ByteString
      getUidBytes();

  /**
   * <pre>
   *发送目标id
   * </pre>
   *
   * <code>string objId = 4;</code>
   */
  java.lang.String getObjId();
  /**
   * <pre>
   *发送目标id
   * </pre>
   *
   * <code>string objId = 4;</code>
   */
  com.google.protobuf.ByteString
      getObjIdBytes();

  /**
   * <pre>
   *消息发送时间
   * </pre>
   *
   * <code>int64 time = 5;</code>
   */
  long getTime();
}
