// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UcenterService.proto

package com.fireflyi.gerant.rpclient.route;

public final class UcenterServicePtc {
  private UcenterServicePtc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024UcenterService.proto\022\016protocol.route\032\r" +
      "Greqptc.proto\032\rGresptc.proto2\231\001\n\016Ucenter" +
      "Service\022,\n\010register\022\016.protocol.Greq\032\016.pr" +
      "otocol.Gres\"\000\022+\n\007outLine\022\016.protocol.Greq" +
      "\032\016.protocol.Gres\"\000\022,\n\010getUsers\022\016.protoco" +
      "l.Greq\032\016.protocol.Gres\"\000B9\n\"com.fireflyi" +
      ".gerant.rpclient.routeB\021UcenterServicePt" +
      "cP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.fireflyi.gerant.rpclient.protobuf.GreqPtc.getDescriptor(),
          com.fireflyi.gerant.rpclient.protobuf.GresPtc.getDescriptor(),
        });
    com.fireflyi.gerant.rpclient.protobuf.GreqPtc.getDescriptor();
    com.fireflyi.gerant.rpclient.protobuf.GresPtc.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
