// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerNodeInfoVo.proto

package com.fireflyi.gerant.rpclient.route.vo;

public interface ServerNodeInfoVoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.route.ServerNodeInfoVo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *ip
   * </pre>
   *
   * <code>string ip = 1;</code>
   */
  java.lang.String getIp();
  /**
   * <pre>
   *ip
   * </pre>
   *
   * <code>string ip = 1;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>int32 port = 2;</code>
   */
  int getPort();

  /**
   * <pre>
   *名字
   * </pre>
   *
   * <code>string name = 3;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   *名字
   * </pre>
   *
   * <code>string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   *组名
   * </pre>
   *
   * <code>string group = 4;</code>
   */
  java.lang.String getGroup();
  /**
   * <pre>
   *组名
   * </pre>
   *
   * <code>string group = 4;</code>
   */
  com.google.protobuf.ByteString
      getGroupBytes();
}
